version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase ....
      - mvn clean package
  post-build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/service-registry.jar
  discard-paths: yes
